name: HAP
version: 1.19
date: 2019-02-05
description: |
    Homological Algebra Programming

authors:
    - name: Graham Ellis
      url: http://hamilton.nuigalway.ie

maintainers:
    - name: Graham Ellis
      url: http://hamilton.nuigalway.ie

GAP: ">= 4.5.6"

needed-pkgs:
    - name: "polycyclic"
      version: ">=1.1"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "crystcat"
      version: ">=1.1"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap45/packages.php"
    - name: "fga"
      version: ">=1.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "aclib"
      version: ">=1.1"
      url: "https://gap-packages.github.io/aclib/"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=0.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "nq"
      version: ">=1.1"
      url: "http://gap-packages.github.io/nq/"
    - name: "nql"
      version: ">=0.0"
    - name: "homology"
      version: ">=0.0"
    - name: "edim"
      version: ">=1.2.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/EDIM"
    - name: "singular"
      version: ">=06.07.23"
      url: "http://www.gap-system.org/HostedGapPackages/singular/"
    - name: "congruence"
      version: ">=0,0"
      url: "https://gap-packages.github.io/congruence"
    - name: "HAPcryst"
      version: ">0.0"
      url: "http://csserver.evansville.edu/~mroeder/HAPcryst.html"
    - name: "xmod"
      version: ">0.0"
      url: "https://gap-packages.github.io/xmod/"

www: http://hamilton.nuigalway.ie/Hap/www
readme: README.HAP
packageinfo: http://hamilton.nuigalway.ie/Hap/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://hamilton.nuigalway.ie/Hap/hap1.19.tar.gz

abstract: |
    This package provides some functions for group cohomology. 

status: accepted
doc-html: www/index.html
doc-pdf: doc/manual.pdf
keywords: |
    homology, cohomology, resolution, homotopy group, module of identities.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ell19</span>]   <b class='BibAuthor'>Ellis, G.</b>,
     <i class='BibTitle'>HAP, Homological Algebra Programming,
             Version 1.19</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="http://hamilton.nuigalway.ie/Hap/www">http://hamilton.nuigalway.ie/Hap/www</a></span>.
    </p>
    

bibtex: |
    @misc{ HAP1.19,
      author =           {Ellis, G.},
      title =            {{HAP}, Homological Algebra Programming, {V}ersion 1.19},
      month =            {Feb},
      year =             {2019},
      note =             {Refereed GAP package},
      howpublished =     {\href           {http://hamilton.nuigalway.ie/Hap/www}
                          {\texttt{http://hamilton.nuigalway.ie/}\discretionary
                          {}{}{}\texttt{Hap/}\discretionary {}{}{}\texttt{www}}},
      keywords =         {homology;   cohomology;  resolution;  homotopy  group;
                          module of identities},
      printedkey =       {Ell19}
    }

